apiVersion: v1
kind: Namespace
metadata:
  name: finserv-dev-payments
  labels:
    finserv.io/environment: dev
    finserv.io/domain: payments
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: finserv-dev-risk
  labels:
    finserv.io/environment: dev
    finserv.io/domain: risk
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: finserv-dev-customer
  labels:
    finserv.io/environment: dev
    finserv.io/domain: customer
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: finserv-dev-platform
  labels:
    finserv.io/environment: dev
    finserv.io/domain: platform
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
