apiVersion: v1
kind: Namespace
metadata:
  name: finserv-dev-payments
  labels:
    finserv.io/environment: dev
    finserv.io/domain: payments
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: finserv-dev-risk
  labels:
    finserv.io/environment: dev
    finserv.io/domain: risk
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: finserv-dev-customer
  labels:
    finserv.io/environment: dev
    finserv.io/domain: customer
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: finserv-dev-platform
  labels:
    finserv.io/environment: dev
    finserv.io/domain: platform
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: finserv-staging-payments
  labels:
    finserv.io/environment: staging
    finserv.io/domain: payments
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: finserv-staging-risk
  labels:
    finserv.io/environment: staging
    finserv.io/domain: risk
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: finserv-staging-customer
  labels:
    finserv.io/environment: staging
    finserv.io/domain: customer
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: finserv-staging-platform
  labels:
    finserv.io/environment: staging
    finserv.io/domain: platform
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: finserv-prod-payments
  labels:
    finserv.io/environment: prod
    finserv.io/domain: payments
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: finserv-prod-risk
  labels:
    finserv.io/environment: prod
    finserv.io/domain: risk
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: finserv-prod-customer
  labels:
    finserv.io/environment: prod
    finserv.io/domain: customer
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: finserv-prod-platform
  labels:
    finserv.io/environment: prod
    finserv.io/domain: platform
    istio-injection: enabled
